name: 🐛 Bug Report
description: Report a reproducible bug in FarmLink
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Laravel version, etc.
      placeholder: "Windows 10, Chrome 115, Laravel 10"
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What did you do to trigger the bug?
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: Paste logs or attach screenshots
